export const journeeQuotes = {
  vietnam: [
    "The streets slow down after the rain in Hanoi.",
    "Vietnam reveals itself one coffee at a time.",
    "The rhythm of Saigon begins after sunset.",
    "Hoi An keeps its best light close to the river.",
    "In Da Nang, the morning starts with sea air and scooter engines.",
    "Hanoi teaches you to listen between the horns.",
    "Saigon moves quickly, but the coffee asks you to stay.",
    "The Mekong feels less like a place than a way of moving.",
    "A bowl of pho can reset an entire morning.",
    "Hue carries its history quietly, under rain and royal walls.",
    "Sapa changes mood with the clouds.",
    "Vietnam's best days often begin in an alley.",
    "Lantern light makes Hoi An feel half remembered.",
    "In Ninh Binh, the river does most of the speaking.",
    "The coast of Vietnam knows how to lower the volume.",
    "Saigon after dark is all steam, neon, and late decisions.",
  ],
  japan: [
    "Tokyo feels quieter the deeper you look.",
    "Kyoto speaks softly through detail.",
    "The stillness is part of the journey.",
    "Japan rewards the traveler who notices small things.",
    "Kyoto is most honest before the tour buses arrive.",
    "Tokyo changes pace at every station.",
    "A train in Japan can make distance feel deliberate.",
    "The best meal in Tokyo may be behind a curtain and six seats.",
    "Osaka tells the truth through appetite.",
    "In Nara, the afternoon seems to walk slower.",
    "Hokkaido leaves room for silence.",
    "Rain makes Tokyo feel newly private.",
    "Kyoto gardens do not perform. They wait.",
    "Japan's elegance is often practical first.",
    "The vending machine glow is part of the city at night.",
    "Some temples are less seen than overheard.",
  ],
  italy: [
    "Some dinners in Italy last longer than the itinerary.",
    "Milan moves fast. Tuscany does not.",
    "A train through Italy changes pace and perspective.",
    "Rome is built from appetite, stone, and argument.",
    "Florence keeps beauty close enough to interrupt your plans.",
    "Venice sounds different before the first boat crowd.",
    "Naples does not soften itself for visitors.",
    "The Dolomites make silence feel architectural.",
    "Sicily lingers in the heat after lunch.",
    "In Bologna, the day often improves around the table.",
    "Lake Como makes time feel expensive without trying.",
    "Italy is at its best when the schedule loses authority.",
    "A late train, a good espresso, and suddenly the plan works.",
    "Tuscany moves in long shadows and second glasses.",
    "Milan's elegance is sharper when it rains.",
  ],
  morocco: [
    "Marrakech becomes real after midnight.",
    "The silence beyond the desert matters most.",
    "Fes turns every corner into a question.",
    "The medina does not need straight lines to make sense.",
    "Mint tea slows the room down.",
    "Essaouira carries salt, wind, and blue doors.",
    "In the Sahara, morning arrives without decoration.",
    "Marrakech is color, heat, bargaining, and sudden quiet.",
    "Chefchaouen feels like a pause painted into the mountains.",
    "Morocco teaches direction by texture, not distance.",
    "The desert road is long enough to change the conversation.",
    "Courtyard shade is a kind of luxury.",
    "The call to prayer changes the shape of the evening.",
    "A riad feels hidden until it becomes home.",
  ],
  switzerland: [
    "Switzerland makes precision feel natural.",
    "In Lauterbrunnen, the valley does the talking.",
    "The train window is part of the Swiss itinerary.",
    "Alpine mornings arrive clean and unsentimental.",
    "A lake in Switzerland can make a city feel quieter.",
    "The mountains do not need drama. They have scale.",
    "Zurich keeps its calm close to the water.",
    "The best Swiss days are measured in platforms and weather.",
    "Lauterbrunnen turns every walk into a vertical map.",
  ],
  indonesia: [
    "Ubud wakes through incense, rain, and motorbikes.",
    "Bali is loudest where it pretends to be quiet.",
    "Rice terraces make time feel handmade.",
    "The morning in Ubud begins before the cafes open.",
    "Island rain changes the color of everything.",
    "A temple visit in Bali is also a lesson in pace.",
    "The best parts of Bali happen between roads.",
    "Ubud keeps ceremony in the ordinary hours.",
  ],
  norway: [
    "Lofoten makes distance feel physical.",
    "In Norway, the weather is part of the architecture.",
    "The north has a way of clearing the mind without asking.",
    "Fishing villages in Lofoten look temporary against permanent mountains.",
    "Norwegian silence has weight.",
    "A road in Lofoten rarely feels like just a road.",
    "The light in the north changes the meaning of evening.",
  ],
  greece: [
    "Santorini is best before the white walls become a crowd.",
    "Greek islands understand the value of a slow lunch.",
    "The Aegean turns blue into a daily event.",
    "In Greece, sunset is less a time than a gathering.",
    "A ferry can make the itinerary feel human again.",
    "The village steps decide your pace for you.",
    "Greece keeps its warmth in food, stone, and sea wind.",
  ],
  unitedArabEmirates: [
    "Dubai is ambition made visible before breakfast.",
    "The desert sits just beyond the glass towers, patient and older.",
    "Dubai nights move in reflections.",
    "The creek remembers a slower city.",
    "In Dubai, scale is part of the weather.",
    "A quiet majlis can outlast the skyline.",
  ],
  unitedStates: [
    "New York runs on appetite, weather, and nerve.",
    "The city changes block by block, not borough by borough.",
    "A corner diner can explain New York better than a viewpoint.",
    "Manhattan is most honest in bad weather.",
    "The subway gives the city its pulse.",
    "New York rewards the traveler who keeps walking.",
  ],
  argentina: [
    "Patagonia makes plans feel smaller in the best way.",
    "The wind in Patagonia is not background.",
    "A trail in Patagonia teaches patience quickly.",
    "The southern light makes distance look clean.",
    "In Patagonia, silence has edges.",
    "The mountains arrive slowly, then all at once.",
  ],
  canada: [
    "Banff makes the morning feel newly made.",
    "The Canadian Rockies do scale without performance.",
    "A lake in Banff can stop a conversation mid-sentence.",
    "Mountain weather keeps the day honest.",
    "The road to Banff is part of the arrival.",
    "Cold air sharpens every color.",
  ],
  southAfrica: [
    "Cape Town holds mountain, ocean, and history in the same breath.",
    "The city changes tone when Table Mountain disappears in cloud.",
    "Cape Town's best meals often come with sea wind.",
    "The coastline keeps pulling the day outward.",
    "In Cape Town, beauty and complexity share the view.",
    "Morning light makes the mountain feel close enough to touch.",
  ],
  peru: [
    "Machu Picchu is quietest when the mist has work to do.",
    "Peru carries altitude in the body and memory in the stone.",
    "The Sacred Valley asks for slower breathing.",
    "Cusco makes history feel lived-in.",
    "A train through the valley changes the day before arrival.",
    "The Andes make silence feel ancient.",
  ],
  southKorea: [
    "Seoul changes speed without warning.",
    "The best Seoul nights begin with one more side dish.",
    "A palace wall can make the city exhale.",
    "Seoul is neon, mountain air, and precise little rituals.",
    "Rain makes the alleys feel cinematic.",
    "The cafe is never just a cafe in Seoul.",
  ],
  thailand: [
    "Bangkok starts early and refuses to end neatly.",
    "The city is heat, river light, and late noodles.",
    "Bangkok's rhythm is easier to feel than explain.",
    "A night market can rearrange the whole day.",
    "Temple gold looks different after rain.",
    "The river gives Bangkok another tempo.",
  ],
  denmark: [
    "The Faroe Islands make weather the main character.",
    "In the Faroes, roads feel drawn by patience.",
    "Grass roofs and sea cliffs keep the palette honest.",
    "The islands do not rush to be understood.",
    "Fog turns every village into a rumor.",
    "The North Atlantic decides the mood first.",
  ],
  tropics: [
    "The tropics move by shade, tide, and sudden rain.",
    "Island time is not slower. It is less interested in control.",
    "The coast changes the body's idea of urgency.",
    "A tropical morning is best before the heat gets organized.",
    "Salt air has a way of editing the plan.",
  ],
  globalCities: [
    "Some cities only explain themselves after dinner.",
    "Night food streets are the unofficial map.",
    "A city becomes readable when you follow the smoke.",
    "The best urban rhythm is usually off the main avenue.",
    "Late trains and open kitchens make a city feel alive.",
  ],
  greenBelt: [
    "Rainforest days begin in layers of sound.",
    "A waterfall changes the temperature of the whole afternoon.",
    "The green belt rewards travelers who stop talking.",
    "Mist makes the path feel newly discovered.",
    "The forest keeps its own calendar.",
  ],
} as const;

export type JourneeQuoteKey = keyof typeof journeeQuotes;

type DestinationQuoteInput = {
  city?: string;
  country?: string;
};

const countryQuoteKeys: Record<string, JourneeQuoteKey> = {
  argentina: "argentina",
  canada: "canada",
  denmark: "denmark",
  greece: "greece",
  indonesia: "indonesia",
  italy: "italy",
  japan: "japan",
  morocco: "morocco",
  norway: "norway",
  peru: "peru",
  switzerland: "switzerland",
  thailand: "thailand",
  vietnam: "vietnam",
  "south africa": "southAfrica",
  "south korea": "southKorea",
  "the tropics": "tropics",
  "global cities": "globalCities",
  "the green belt": "greenBelt",
  "united arab emirates": "unitedArabEmirates",
  "united states": "unitedStates",
};

const cityQuoteKeys: Record<string, JourneeQuoteKey> = {
  bangkok: "thailand",
  banff: "canada",
  "cape town": "southAfrica",
  "coastal islands": "tropics",
  dolomites: "italy",
  dubai: "unitedArabEmirates",
  "faroe islands": "denmark",
  "ho chi minh city": "vietnam",
  "hoi an": "vietnam",
  kyoto: "japan",
  "lauterbrunnen valley": "switzerland",
  "lofoten islands": "norway",
  "machu picchu": "peru",
  marrakech: "morocco",
  "new york": "unitedStates",
  "night food streets": "globalCities",
  patagonia: "argentina",
  "rainforest falls": "greenBelt",
  santorini: "greece",
  "sahara road": "morocco",
  seoul: "southKorea",
  ubud: "indonesia",
};

function normalizeDestinationKey(value?: string) {
  return value?.trim().toLowerCase() ?? "";
}

export function getJourneeQuoteKey({
  city,
  country,
}: DestinationQuoteInput): JourneeQuoteKey {
  const cityKey = cityQuoteKeys[normalizeDestinationKey(city)];
  if (cityKey) return cityKey;

  const countryKey = countryQuoteKeys[normalizeDestinationKey(country)];
  if (countryKey) return countryKey;

  return "globalCities";
}

export function getJourneeQuotesForDestination(input: DestinationQuoteInput) {
  return journeeQuotes[getJourneeQuoteKey(input)];
}
